export const S = {
  appTitle: "pi-model-failover",
  tabs: ["Model Manager", "Chains", "History", "Settings"],
  memoryMode: "[memory mode]",
  needsTui: "pi-model-failover needs the TUI",
  commandDescription: "Manage providers, failover chains, history",
  // biome-ignore format: keep model switch strings together
  modelSwitch: { selected: (ref: string) => `Using ${ref}`, unavailable: "Selected model is not available", authMissing: (ref: string) => `No configured authentication for ${ref}`, failed: "Could not switch model" },
  serverQualityDisabledWarning:
    "Server Quality timers are disabled; requests may wait until the provider or Pi aborts.",
  modelsJsonInvalid: "models.json is invalid",
  sharedState: {
    invalid: "state.json is invalid; using memory mode",
    newerVersion: "state.json uses a newer version; using memory mode",
  },
  // biome-ignore format: keep registrar strings together
  ...{ registrar: { builtinSkipped: (id: string) => `Skipping built-in provider ${id}`, registrationFailed: (id: string) => `Failed to register provider ${id}` }, footer: { current: (target: string) => target, fallback: (target: string, reason?: string) => reason === undefined ? target : `${target} <- ${reason}` } },
  settingsHeader: "Global settings (targets without a value use these)",
  // biome-ignore format: keep settings table strings together
  settings: { tableHeader: "Setting  Value", labels: {
      listRows: "List rows",
      ttftTimeoutSeconds: "TTFT timeout seconds",
      serverQualityEnabled: "Server Quality enabled", serverQualityTtft: "Server Quality TTFT", serverQualityNoProgress: "Server Quality no-progress",
      maxRetries: "Max retries",
      errorHandlingMode: "Error handling mode",
      noProgressTimeoutSeconds: "No-progress timeout seconds",
    },
    options: {
      serverQuality: { on: "on", off: "off" },
      errorHandlingMode: {
        smart: "Smart",
        switch: "Switch",
        retry: "Retry",
      },
    },
  },
  resetAll: "Reset all cooldowns and manual recovery",
  resetAllConfirm: (n: number) => `Reset ${n} targets?`,
  emptyList: "Nothing here yet",
  history: {
    header: "When  Chain  From  To  Reason  ms",
    dropped: (count: number) => `(${count} dropped)`,
    detailHeader: "Event details",
    none: "-",
    reset: "reset",
    unknownTime: "unknown time",
    refreshFailed: "Could not refresh history",
    resetFailed: "Could not reset target",
    // biome-ignore format: keep history filter strings together
    filter: { title: (kind: string) => (kind === "chain" ? "Filter by Chain" : "Filter by provider") },
  },
  modelManager: {
    providerHeader: "Provider  API  Models  Mult  Owner",
    modelHeader: "Model  ctx  max  reasoning",
    keyLabel: "key",
    missingKey: "-",
    contextLabel: "ctx",
    maxTokensLabel: "max",
    reasoningLabel: "reasoning",
    notReasoning: "-",
    failoverOwner: "failover",
    pmmOwner: "pmm",
    multiplierSuffix: "x",
    driftMarker: "~",
    keyGroupForm: {
      title: "Batch add API keys",
      keyEntryTitle: "Enter API keys",
      labels: {
        prefix: "Prefix",
        baseUrl: "Base URL",
        api: "API type",
        headers: "Headers",
        multiplier: "Multiplier",
        keys: "Keys",
      },
      keysHint: "(one per line, optional key multiplier)",
      apiOptions: [
        "openai-completions",
        "openai-responses",
        "anthropic-messages",
        "google-generative-ai",
      ],
      invalidPrefix: "Prefix is required and must not contain whitespace or slash",
      invalidUrl: "Base URL must be a valid http or https URL",
      invalidApi: "Select a supported API type",
      invalidHeaders: "Headers must use Name: value lines",
      emptyKeys: "At least one key is required",
      invalidKeyLine: "Each key line must be key or key multiplier",
      invalidMultiplier: "Multiplier must be positive and finite",
      saved: "Key group saved",
      cancelled: "Key group canceled",
      saveFailed: "Could not save key group",
    },
    providerForm: {
      title: "Provider",
      addTitle: "Add provider",
      editTitle: "Edit provider",
      renameTitle: "Rename provider",
      multiplierTitle: "Edit multiplier",
      labels: {
        id: "ID",
        name: "Name",
        baseUrl: "Base URL",
        api: "API type",
        apiKey: "API key",
        authHeader: "Auth header",
        headers: "Headers",
        multiplier: "Multiplier",
      },
      invalidName: "Name is required and must not contain whitespace or slash",
      invalidId: "ID is required and must not contain whitespace or slash",
      duplicateId: "ID is already in use",
      invalidUrl: "Base URL must be a valid http or https URL",
      invalidApi: "Select a supported API type",
      invalidHeaders: "Headers must use Name: value lines",
      invalidMultiplier: "Multiplier must be positive and finite",
      saveFailed: "Could not save provider",
    },
    modelForm: {
      title: "Edit Provider Model",
      labels: {
        name: "Name",
        reasoning: "Reasoning",
        input: "Input",
        contextWindow: "Context window",
        maxTokens: "Max tokens",
        costInput: "Input cost",
        costOutput: "Output cost",
        costCacheRead: "Cache-read cost",
        costCacheWrite: "Cache-write cost",
      },
      boolean: { yes: "yes", no: "no" },
      inputOptions: ["text", "image"],
      invalidNumbers: "Model limits and costs must be finite",
      missingModel: "Provider Model was not found",
      saveFailed: "Could not save Provider Model",
    },
    actions: {
      deleteProviderTitle: (id: string) => `Delete provider ${id}?`,
      deleteProviderDetails: "Only the provider node will be removed",
      deleteProviderAffected: (names: string[]) => {
        if (names.length === 0) return "No Chains reference this provider";
        const plural = names.length === 1 ? "" : "s";
        return `It is a target in ${names.length} Chain${plural}: ${names.join(", ")}`;
      },
      deleteProviderCleanup: "Affected Chain targets and Virtual Models will be updated",
      removeModelsTitle: (count: number) =>
        `Remove ${count} Provider Model${count === 1 ? "" : "s"}?`,
      removeModelsDetails: "Selected Provider Models will be removed",
      syncTitle: (count: number) => `Sync ${count} Provider Model${count === 1 ? "" : "s"}?`,
      syncDetails: "Catalog values replace four model attributes",
      saveFailed: "Could not save Model Manager changes",
    },
    catalog: {
      title: "Catalog",
      header: (count: number) => `Catalog (${count})`,
      tableHeader: "Model  Name  ctx  max  reasoning  vision",
      providerHeader: "Provider  URL  API  key",
      endpointProviderHeader: "Endpoint providers",
      endpointModelsHeader: "Endpoint models",
      builtinHeader: "Pi built-in models",
      providerTargetsHeader: "Add to providers",
      manualTitle: "Manual catalog model",
      labels: {
        id: "Model id",
        name: "Name",
        reasoning: "Reasoning",
        vision: "Vision",
        contextWindow: "Context window",
        maxTokens: "Max tokens",
      },
      boolean: { yes: "yes", no: "no" },
      invalidId: "Model id is required",
      invalidNumbers: "Model limits must be finite",
      endpointImportFailed: "Could not import endpoint models",
      builtinImportFailed: "Could not import Pi built-in models",
      saveFailed: "Could not save catalog",
      deleteTitle: (count: number) => `Delete ${count} catalog model${count === 1 ? "" : "s"}?`,
      deleteDetails: "Selected catalog models will be removed",
      providerModelsUntouched: "Provider Models remain unchanged",
    },
  },
  chains: {
    listHeader: "Chain  Targets  First target  Status",
    targetLabels: {
      index: "#",
      target: "Target",
      multiplier: "Mult",
      status: "Status",
    },
    detailHeader: (id: string, virtualId: string, details: string) =>
      `${id} → ${virtualId}  ${details}`,
    virtualId: (id: string) => `failover/${id}`,
    virtualDetails: (contextWindow: number, reasoning: string, input: string) =>
      `ctx ${contextWindow}  reasoning ${reasoning}  input ${input}`,
    noTarget: "-",
    notRegistered: "not registered",
    reasoning: { yes: "yes", no: "-" },
    status: {
      ok: "ok",
      manual: "manual",
      cool: (minutes: number) => `cool ${minutes}m`,
      summary: (cooling: number, manual: number) => {
        const parts: string[] = [];
        if (cooling > 0) parts.push(`${cooling} cooling`);
        if (manual > 0) parts.push(`${manual} manual`);
        return parts.join(", ") || S.chains.status.ok;
      },
    },
    form: {
      newTitle: "New chain",
      renameTitle: "Rename chain",
      labels: { id: "ID", name: "Name" },
      invalidId: "Chain id must match lowercase letters, digits, and hyphens",
      duplicateId: "Chain id is already in use",
      invalidName: "Chain name is required",
      saveFailed: "Could not save Chain changes",
    },
    targetForm: {
      title: (ref: string) => `Target ${ref}`,
      labels: {
        errorHandlingMode: "Error handling mode",
        maxRetries: "Max retries",
        reasoningEffort: "Reasoning effort",
        noProgressTimeoutSeconds: "No-progress timeout seconds",
        ttftTimeoutSeconds: "TTFT timeout seconds",
        serverQualityEnabled: "Server Quality enabled",
        serverQualityTtft: "Server Quality TTFT",
        serverQualityNoProgress: "Server Quality no-progress",
        modelParameters: "Model parameters (JSON)",
      },
      options: {
        errorHandlingMode: {
          smart: "Smart",
          switch: "Switch",
          retry: "Retry",
        },
        reasoningEffort: {
          inherit: "inherit",
          off: "off",
          low: "low",
          medium: "medium",
          high: "high",
          xhigh: "xhigh",
          max: "max",
        },
        serverQuality: { inherit: "inherit", on: "on", off: "off" },
      },
      invalidParameters: "Model parameters must be a JSON object",
      saveFailed: "Could not save Target settings",
    },
    import: {
      allTitle: "Add targets from models.json",
      title: (modelId: string) => `Import providers for ${modelId}`,
      existing: "already in Chain",
      add: "add",
      saveFailed: "Could not import providers",
    },
    actions: {
      deleteTitle: (id: string) => `Delete chain ${id}?`,
      deleteDetails: "The Chain and its Virtual Model will be removed",
      resetTitle: (id: string, count: number) => `Reset ${count} targets in ${id}?`,
      resetDetails: "Cooldowns and Manual Recovery are cleared",
      removeTargetTitle: (ref: string) => `Remove target ${ref}?`,
      removeTargetDetails: "The target will be removed from this Chain",
    },
  },
  form: {
    inputTitle: (label: string) => `Input ${label}`,
    inputPrompt: "Value",
    cursor: "▌",
    inputHint: "Enter commit · Ctrl+S save · Esc cancel",
  },
  filter: { inputTitle: "Filter list", inputHint: "Enter apply · Esc cancel" },
  confirm: "Confirm",
  cancel: "Cancel",
  hints: {
    global: Object.entries({ Tab: "next tab", "?": "help", q: "quit" }),
    modelManager: {
      list: [
        ["Enter", "open"],
        ["a", "add provider"],
        ["d", "delete provider"],
        ["m", "multiplier"],
        ["/", "filter"],
        ["r", "rename"],
        ["↑↓", "move"],
        ["k", "batch keys"],
        ["c", "catalog"],
        ["?", "help"],
        ["q", "quit"],
      ] as Array<[string, string]>,
      detail: [
        ["Enter", "edit model"],
        ["p", "use model"],
        ["a", "add from catalog"],
        ["d", "remove model"],
        ["s", "sync attributes"],
        ["e", "edit provider"],
        ["Space", "mark"],
        ["/", "filter models"],
        ["↑↓", "move"],
        ["Esc", "back"],
        ["?", "help"],
        ["q", "quit"],
      ] as Array<[string, string]>,
      catalog: [
        ["Space", "mark"],
        ["a", "all"],
        ["n", "none"],
        ["Enter", "providers"],
        ["i", "endpoint import"],
        ["p", "Pi import"],
        ["+", "manual add"],
        ["e", "edit"],
        ["d", "delete"],
        ["/", "filter"],
        ["Esc", "back"],
      ] as Array<[string, string]>,
      catalogSelect: [
        ["Space", "mark"],
        ["a", "all"],
        ["n", "none"],
        ["Enter", "confirm"],
        ["/", "filter"],
        ["Esc", "back"],
      ] as Array<[string, string]>,
    },
    chains: {
      list: [
        ["Enter", "open"],
        ["p", "use failover Chain"],
        ["a", "new chain"],
        ["d", "delete"],
        ["r", "rename"],
        ["R", "reset all"],
        ["/", "filter"],
        ["↑↓", "move"],
        ["?", "help"],
        ["q", "quit"],
      ] as Array<[string, string]>,
      detail: [
        ["Enter", "target settings"],
        ["p", "use failover Chain"],
        ["a", "add target"],
        ["i", "same-model import"],
        ["d", "remove target"],
        ["J/K", "move target"],
        ["s", "sort by multiplier"],
        ["r", "reset target"],
        ["/", "filter"],
        ["Esc", "back"],
        ["?", "help"],
        ["q", "quit"],
      ] as Array<[string, string]>,
    },
    history: {
      list: [
        ["Enter", "details"],
        ["f", "filter chain"],
        ["p", "filter provider"],
        ["c", "clear filter"],
        ["r", "reset target"],
        ["g", "refresh"],
        ["/", "filter"],
        ["↑↓", "move"],
        ["?", "help"],
        ["q", "quit"],
      ] as Array<[string, string]>,
      detail: [
        ["↑↓", "scroll"],
        ["r", "reset target"],
        ["Esc", "back"],
        ["?", "help"],
        ["q", "quit"],
      ] as Array<[string, string]>,
      filter: [
        ["↑↓", "move"],
        ["Enter", "select"],
        ["/", "filter"],
        ["Esc", "cancel"],
        ["c", "clear filter"],
      ] as Array<[string, string]>,
    },
    // biome-ignore format: keep settings hint entries compact
    settings: [["↑↓", "field"], ["Enter", "edit"], ["Ctrl+S", "save"], ["?", "help"], ["q", "quit"]] as Array<[string, string]>,
    // biome-ignore format: keep form hint entries compact
    form: [["Enter", "edit / commit"], ["Ctrl+S", "save"], ["↑↓", "move/select"], ["Tab", "next field"], ["Shift+Tab", "prev"], ["Space", "toggle"], ["Esc", "cancel"]] as Array<[string, string]>,
    keyEntry: Object.entries({ Enter: "commit row", "Ctrl+S": "save and return", Esc: "cancel" }),
    confirm: [
      ["Tab", "choose confirm or cancel"],
      ["Enter", "confirm action"],
      ["Esc", "cancel without saving changes"],
    ] as Array<[string, string]>,
  },
  help: { global: "Global", listRowsHint: "(5–20)", zeroDisables: "(0 disables)" },
} as const;
