export const S = {
  appTitle: "pi-model-failover",
  tabs: ["Model Manager", "Chains", "History", "Settings"],
  memoryMode: "[memory mode]",
  needsTui: "pi-model-failover needs the TUI",
  commandDescription: "Manage providers, failover chains, history",
  abortWarning:
    "Aborting still bills the prompt tokens of the aborted request on most providers/relays.",
  modelsJsonInvalid: "models.json is invalid",
  sharedState: {
    invalid: "state.json is invalid; using memory mode",
    newerVersion: "state.json uses a newer version; using memory mode",
  },
  registrar: {
    builtinSkipped: (id: string) => `Skipping built-in provider ${id}`,
    registrationFailed: (id: string) => `Failed to register provider ${id}`,
  },
  settingsHeader: "Global settings (targets without a value use these)",
  settings: {
    labels: {
      listRows: "List rows",
      ttftTimeoutSeconds: "TTFT timeout seconds",
      ttftAction: "TTFT action",
      maxRetries: "Max retries",
      errorHandlingMode: "Error handling mode",
      noProgressTimeoutSeconds: "No-progress timeout seconds",
    },
    options: {
      ttftAction: {
        cooldownOnly: "Cooldown only",
        abort: "Abort",
      },
      errorHandlingMode: {
        smart: "Smart",
        switch: "Switch",
        retry: "Retry",
      },
    },
  },
  resetAll: "Reset all cooldowns and manual recovery",
  resetAllConfirm: (n: number) => `Reset ${n} targets?`,
  emptyList: "Nothing here yet",
  history: {
    header: "When  Chain  From  To  Reason  ms",
    headerDropped: (count: number) => `When  Chain  From  To  Reason  ms  (${count} dropped)`,
    detailHeader: "Event details",
    row: (when: string, chain: string, from: string, to: string, reason: string, elapsed: number) =>
      `${when}  ${chain}  ${from}  ${to}  ${reason}  ${elapsed}`,
    none: "-",
    reset: "reset",
    unknownTime: "unknown time",
    refreshFailed: "Could not refresh history",
    resetFailed: "Could not reset target",
    filter: {
      title: (kind: string) => (kind === "chain" ? "Filter by Chain" : "Filter by provider"),
    },
  },
  modelManager: {
    providerHeader: "Provider  API  Models  Mult  Owner",
    keyLabel: "key",
    missingKey: "-",
    contextLabel: "ctx",
    maxTokensLabel: "max",
    reasoningLabel: "reasoning",
    notReasoning: "-",
    failoverOwner: "failover",
    pmmOwner: "pmm",
    multiplierSuffix: "x",
    driftMarker: "~",
    keyGroupForm: {
      title: "Batch add API keys",
      labels: {
        prefix: "Prefix",
        baseUrl: "Base URL",
        api: "API type",
        headers: "Headers",
        multiplier: "Multiplier",
        keys: "Keys",
      },
      keysHint: "(one per line, optional key multiplier)",
      apiOptions: [
        "openai-completions",
        "openai-responses",
        "anthropic-messages",
        "google-generative-ai",
      ],
      invalidPrefix: "Prefix is required and must not contain whitespace or slash",
      invalidUrl: "Base URL must be a valid http or https URL",
      invalidApi: "Select a supported API type",
      invalidHeaders: "Headers must use Name: value lines",
      emptyKeys: "At least one key is required",
      invalidKeyLine: "Each key line must be key or key multiplier",
      invalidMultiplier: "Multiplier must be positive and finite",
      saved: "Key group saved",
      cancelled: "Key group canceled",
      saveFailed: "Could not save key group",
    },
    providerForm: {
      title: "Provider",
      addTitle: "Add provider",
      editTitle: "Edit provider",
      renameTitle: "Rename provider",
      multiplierTitle: "Edit multiplier",
      labels: {
        name: "Name",
        baseUrl: "Base URL",
        api: "API type",
        apiKey: "API key",
        authHeader: "Auth header",
        headers: "Headers",
        multiplier: "Multiplier",
      },
      invalidName: "Name is required and must not contain whitespace or slash",
      invalidUrl: "Base URL must be a valid http or https URL",
      invalidApi: "Select a supported API type",
      invalidHeaders: "Headers must use Name: value lines",
      invalidMultiplier: "Multiplier must be positive and finite",
      saveFailed: "Could not save provider",
    },
    modelForm: {
      title: "Edit Provider Model",
      labels: {
        name: "Name",
        reasoning: "Reasoning",
        input: "Input",
        contextWindow: "Context window",
        maxTokens: "Max tokens",
        costInput: "Input cost",
        costOutput: "Output cost",
        costCacheRead: "Cache-read cost",
        costCacheWrite: "Cache-write cost",
      },
      boolean: { yes: "yes", no: "no" },
      inputOptions: ["text", "image"],
      invalidNumbers: "Model limits and costs must be finite",
      missingModel: "Provider Model was not found",
      saveFailed: "Could not save Provider Model",
    },
    actions: {
      deleteProviderTitle: (id: string) => `Delete provider ${id}?`,
      deleteProviderDetails: "Only the provider node will be removed",
      deleteProviderAffected: (names: string[]) =>
        names.length === 0
          ? "No Chains reference this provider"
          : `It is a target in ${names.length} Chain${names.length === 1 ? "" : "s"}: ${names.join(", ")}`,
      deleteProviderCleanup: "Affected Chain targets and Virtual Models will be updated",
      removeModelsTitle: (count: number) =>
        `Remove ${count} Provider Model${count === 1 ? "" : "s"}?`,
      removeModelsDetails: "Selected Provider Models will be removed",
      syncTitle: (count: number) => `Sync ${count} Provider Model${count === 1 ? "" : "s"}?`,
      syncDetails: "Catalog values replace four model attributes",
      saveFailed: "Could not save Model Manager changes",
    },
    catalog: {
      title: "Catalog",
      header: (count: number) => `Catalog (${count})`,
      endpointProviderHeader: "Endpoint providers",
      endpointModelsHeader: "Endpoint models",
      builtinHeader: "Pi built-in models",
      providerTargetsHeader: "Add to providers",
      manualTitle: "Manual catalog model",
      labels: {
        id: "Model id",
        name: "Name",
        reasoning: "Reasoning",
        vision: "Vision",
        contextWindow: "Context window",
        maxTokens: "Max tokens",
      },
      boolean: { yes: "yes", no: "no" },
      invalidId: "Model id is required",
      invalidNumbers: "Model limits must be finite",
      endpointImportFailed: "Could not import endpoint models",
      builtinImportFailed: "Could not import Pi built-in models",
      saveFailed: "Could not save catalog",
      deleteTitle: (count: number) => `Delete ${count} catalog model${count === 1 ? "" : "s"}?`,
      deleteDetails: "Selected catalog models will be removed",
      providerModelsUntouched: "Provider Models remain unchanged",
    },
  },
  chains: {
    listHeader: "Chain  Targets  First target  Status",
    detailHeader: (id: string, virtualId: string, details: string) =>
      `${id} → ${virtualId}  ${details}`,
    virtualId: (id: string) => `failover/${id}`,
    virtualDetails: (contextWindow: number, reasoning: string, input: string) =>
      `ctx ${contextWindow}  reasoning ${reasoning}  input ${input}`,
    chainRow: (id: string, count: number, first: string, status: string) =>
      `${id}  ${count}  ${first}  ${status}`,
    targetRow: (
      index: number,
      ref: string,
      multiplier: string,
      mode: string,
      retries: number,
      ttft: number,
      action: string,
      status: string,
    ) => `${index} ${ref}  ${multiplier}x  ${mode}  r${retries}  ttft${ttft}/${action}  ${status}`,
    noTarget: "-",
    notRegistered: "not registered",
    reasoning: { yes: "yes", no: "-" },
    status: {
      ok: "ok",
      manual: "manual",
      cool: (minutes: number) => `cool ${minutes}m`,
      summary: (cooling: number, manual: number) => {
        const parts: string[] = [];
        if (cooling > 0) parts.push(`${cooling} cooling`);
        if (manual > 0) parts.push(`${manual} manual`);
        return parts.join(", ") || S.chains.status.ok;
      },
    },
    form: {
      newTitle: "New chain",
      renameTitle: "Rename chain",
      labels: { id: "ID", name: "Name" },
      invalidId: "Chain id must match lowercase letters, digits, and hyphens",
      duplicateId: "Chain id is already in use",
      invalidName: "Chain name is required",
      saveFailed: "Could not save Chain changes",
    },
    targetForm: {
      title: (ref: string) => `Target ${ref}`,
      labels: {
        errorHandlingMode: "Error handling mode",
        maxRetries: "Max retries",
        reasoningEffort: "Reasoning effort",
        noProgressTimeoutSeconds: "No-progress timeout seconds",
        ttftTimeoutSeconds: "TTFT timeout seconds",
        ttftAction: "TTFT action",
        modelParameters: "Model parameters (JSON)",
      },
      options: {
        errorHandlingMode: {
          smart: "Smart",
          switch: "Switch",
          retry: "Retry",
        },
        reasoningEffort: {
          inherit: "inherit",
          minimal: "minimal",
          low: "low",
          medium: "medium",
          high: "high",
        },
        ttftAction: {
          cooldownOnly: "Cooldown only",
          abort: "Abort",
        },
      },
      invalidParameters: "Model parameters must be a JSON object",
      saveFailed: "Could not save Target settings",
    },
    import: {
      allTitle: "Add targets from models.json",
      title: (modelId: string) => `Import providers for ${modelId}`,
      existing: "already in Chain",
      add: "add",
      saveFailed: "Could not import providers",
    },
    actions: {
      deleteTitle: (id: string) => `Delete chain ${id}?`,
      deleteDetails: "The Chain and its Virtual Model will be removed",
      resetTitle: (id: string, count: number) => `Reset ${count} targets in ${id}?`,
      resetDetails: "Cooldowns and Manual Recovery are cleared",
      removeTargetTitle: (ref: string) => `Remove target ${ref}?`,
      removeTargetDetails: "The target will be removed from this Chain",
    },
  },
  form: {
    inputTitle: (label: string) => `Input ${label}`,
    inputPrompt: "Value",
    inputHint: "Enter save · Esc cancel",
  },
  confirm: "Confirm",
  cancel: "Cancel",
  hints: {
    global: [
      ["Tab", "next tab"],
      ["?", "help"],
      ["q", "quit"],
    ] as Array<[string, string]>,
    modelManager: {
      list: [
        ["Enter", "open"],
        ["a", "add provider"],
        ["d", "delete provider"],
        ["m", "multiplier"],
        ["r", "rename"],
        ["↑↓", "move"],
        ["k", "batch keys"],
        ["c", "catalog"],
        ["?", "help"],
        ["q", "quit"],
      ] as Array<[string, string]>,
      detail: [
        ["Enter", "edit model"],
        ["a", "add from catalog"],
        ["d", "remove model"],
        ["s", "sync attributes"],
        ["e", "edit provider"],
        ["Space", "mark"],
        ["↑↓", "move"],
        ["Esc", "back"],
        ["?", "help"],
        ["q", "quit"],
      ] as Array<[string, string]>,
      catalog: [
        ["Space", "mark"],
        ["a", "all"],
        ["n", "none"],
        ["Enter", "providers"],
        ["i", "endpoint import"],
        ["p", "Pi import"],
        ["+", "manual add"],
        ["e", "edit"],
        ["d", "delete"],
        ["Esc", "back"],
      ] as Array<[string, string]>,
      catalogSelect: [
        ["Space", "mark"],
        ["a", "all"],
        ["n", "none"],
        ["Enter", "confirm"],
        ["Esc", "back"],
      ] as Array<[string, string]>,
    },
    chains: {
      list: [
        ["Enter", "open"],
        ["a", "new chain"],
        ["d", "delete"],
        ["r", "rename"],
        ["R", "reset all"],
        ["↑↓", "move"],
        ["?", "help"],
        ["q", "quit"],
      ] as Array<[string, string]>,
      detail: [
        ["Enter", "target settings"],
        ["a", "add target"],
        ["i", "same-model import"],
        ["d", "remove target"],
        ["J/K", "move target"],
        ["r", "reset target"],
        ["Esc", "back"],
        ["?", "help"],
        ["q", "quit"],
      ] as Array<[string, string]>,
    },
    history: {
      list: [
        ["Enter", "details"],
        ["f", "filter chain"],
        ["p", "filter provider"],
        ["c", "clear filter"],
        ["r", "reset target"],
        ["g", "refresh"],
        ["↑↓", "move"],
        ["?", "help"],
        ["q", "quit"],
      ] as Array<[string, string]>,
      detail: [
        ["↑↓", "scroll"],
        ["r", "reset target"],
        ["Esc", "back"],
        ["?", "help"],
        ["q", "quit"],
      ] as Array<[string, string]>,
      filter: [
        ["↑↓", "move"],
        ["Enter", "select"],
        ["Esc", "cancel"],
        ["c", "clear filter"],
      ] as Array<[string, string]>,
    },
    settings: [
      ["↑↓", "field"],
      ["Enter", "edit or save"],
      ["?", "help"],
      ["q", "quit"],
    ] as Array<[string, string]>,
    form: [
      ["Enter", "edit field"],
      ["↑↓", "move/select"],
      ["Tab", "next field"],
      ["Shift+Tab", "prev"],
      ["Space", "toggle"],
      ["Esc", "cancel"],
    ] as Array<[string, string]>,
    confirm: [
      ["Tab", "choose confirm or cancel"],
      ["Enter", "confirm action"],
      ["Esc", "cancel without saving changes"],
    ] as Array<[string, string]>,
  },
  help: { global: "Global", listRowsHint: "(5–20)", zeroDisables: "(0 disables)" },
} as const;
